### ISSUE TITLE
npm rebuild should be npm install?

### ISSUE THREAD

**Issue by jpike88** [mixmaxhq/eb-fix-npm#14]
https://github.com/mixmaxhq/eb-fix-npm/blob/28c7e6f16de0237d6c91743fde57e76e9484b18a/source/.ebextensions/fix-npm.config#L128

The 'npm rebuild' command seems like a problem... what if new dependencies were added?

**Comment by wearhere** [comment]
package.json shouldn't be changing on a config deploy (a deploy in response to EB dashboard settings changing), only in response to an app deploy.

**Comment by jpike88** [comment]
Dammit... my problem is that npm install isn't correctly running on a new app upgrade, but works fine on a fresh instance! It's driving me insane!

**Comment by wearhere** [comment]
What do you mean by "new app upgrade"? You mean deploying a new version of `package.json`?

**Comment by jpike88** [comment]
package.json could have an additional package for example... do Indeed to do something more drastic than a simple deploy?

**Comment by wearhere** [comment]
If you're deploying a new version of `package.json` that should trigger this flow: https://github.com/mixmaxhq/eb-fix-npm/blob/28c7e6f16de0237d6c91743fde57e76e9484b18a/source/.ebextensions/fix-npm.config#L94

However Mixmax no longer uses this script (in favor of [`eb-disable-npm`](https://github.com/mixmaxhq/eb-disable-npm)), so I can't easily confirm.

**Comment by jpike88** [comment]
I'll try that instead, thanks. This stuff is way more frustrating than it should be!

**Comment by jpike88** [comment]
Just one more thing... how do you ensure the cpu architectures are compatible? Do you use the same docker image, etc? I currently build and deploy from bitrise using the OSX image, and am deploying to the pre-existing Amazon Linux NodeJS AMI... roughly how much work is involved in settling that?

**Comment by wearhere** [comment]
You just have to make sure it's the same OS and memory address width i.e. 32-bit vs. 64-bit.

This means that you will need to build and deploy using a Linux image.

If you're deploying a Node app (as does Mixmax) I wouldn't imagine that you'd need an OS X image to build and deploy. If you're using OS X for development (as does Mixmax) then your build scripts etc. will probably work just fine, most CLI stuff is the same.

Anyhow I'm going to close this, you can file questions about eb-fix-npm on that repo if you like.
